# Generated by Django 6.0 on 2026-01-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grounds", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_opponent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date", models.DateTimeField()),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("draw", "Draw"),
                            ("no_result", "No Result"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ground",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="grounds.ground",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1",
                        to="teams.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2",
                        to="teams.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
