# Generated by Django 5.0.4 on 2026-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_alter_match_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="ball_type",
            field=models.CharField(blank=True, choices=[("leather", "Leather"), ("tennis", "Tennis"), ("other", "Other")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="reporting_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="team_dress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
