# Generated by Django 5.0.4 on 2026-01-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ball_type',
            field=models.CharField(blank=True, choices=[('whiteleather', 'RedLeather'), ('redleather', 'WhiteLeather'), ('pinkleather', 'PinkLeather'), ('tennis', 'Tennis'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
