# Generated by Django 6.0 on 2026-01-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("draw", "Draw"),
                            ("no_result", "No Result"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1",
                        to="teams.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2",
                        to="teams.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_matches",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
