# Generated by Django 6.0 on 2026-01-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0001_initial"),
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="venue",
        ),
        migrations.AddField(
            model_name="match",
            name="external_opponent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="ground",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grounds.ground",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team2",
                to="teams.team",
            ),
        ),
    ]
