# Generated by Django 6.0 on 2026-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("batsman", "Batsman"),
                            ("bowler", "Bowler"),
                            ("all_rounder", "All-Rounder"),
                            ("wicket_keeper", "Wicket-Keeper"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
