# Generated by Django 6.0 on 2026-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
