# Generated by Django 6.0 on 2026-01-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_player_phone_number_player_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="last_payment_date",
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(decimal_places=2, default=750.0, max_digits=10),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
