# Generated by Django 5.0.4 on 2026-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100)),
                ("file", models.FileField(upload_to="media_uploads/")),
                ("media_type", models.CharField(choices=[("photo", "Photo"), ("video", "Video"), ("other", "Other")], max_length=10)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
