# Generated by Django 5.0.4 on 2026-03-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media_gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_media_items", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="media",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
