# Generated by Django 6.0 on 2026-01-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0001_initial"),
        ("players", "0002_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.player",
            ),
        ),
    ]
