# Generated by Django 6.0 on 2026-01-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0002_transaction_player"),
        ("players", "0004_remove_membership_last_payment_date_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="players.player",
            ),
        ),
    ]
