# Generated by Django 6.0 on 2026-01-06 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0003_remove_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("registration", "Registration Fee"),
                    ("monthly", "Monthly Fee"),
                    ("tournament", "Tournament Fee"),
                    ("merchandise", "Merchandise"),
                ],
                default="merchandise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="transaction",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
