# Generated by Django 4.2.27 on 2026-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='brand',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustment',
        ),
    ]
