# Generated by Django 4.2.27 on 2026-01-15 16:07

from django.db import migrations, models
import django.db.models.deletion


def initialize_status_quantities(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    for item in InventoryItem.objects.all():
        if (
            item.available_quantity == 0 and
            item.missing_quantity == 0 and
            item.destroyed_quantity == 0 and
            item.distributed_quantity == 0
        ):
            item.available_quantity = item.quantity
            item.save(update_fields=['available_quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryitem_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/categories/')),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='destroyed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='distributed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='missing_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycategory'),
        ),
        migrations.RunPython(initialize_status_quantities, migrations.RunPython.noop),
    ]
