# Generated by Django 6.0 on 2026-01-07 10:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("registration", "Registration Fee"),
                            ("monthly", "Monthly Fee"),
                            ("tournament", "Tournament Fee"),
                            ("merchandise", "Merchandise"),
                        ],
                        default="merchandise",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField(default=datetime.date.today)),
                ("paid", models.BooleanField(default=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="players.player",
                    ),
                ),
            ],
        ),
    ]
