# Generated by Django 5.0.4 on 2026-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee'), ('tournament', 'Tournament Fee'), ('merchandise', 'Merchandise'), ('fine', 'Fine/Penalty')], default='merchandise', max_length=20),
        ),
    ]
