# Generated by Django 4.2.27 on 2026-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
