# Generated by Django 4.2.27 on 2026-01-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all_rounder', 'All-Rounder'), ('wicket_keeper', 'Wicket-Keeper')], default='all_rounder', max_length=20),
        ),
    ]
