# Generated by Django 5.0.4 on 2026-01-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0002_alter_ground_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ground",
            name="google_map_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
